name: Update Epic Games Offers

on:
  schedule:
    - cron: '0 0 * * *' # يعمل تلقائياً كل يوم في منتصف الليل
  workflow_dispatch:    # يسمح لك بتشغيله يدوياً من GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch Offers
        run: python fetch_epic_deals.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add offers.json
          git commit -m "Update Epic Games offers [EG]" || exit 0
          git push
